In [1]:
# a data point is missing

In [2]:
# there is a linear relationship b/w each factor(input) and target variable(label)
#        eg. as home gets older price tends to decrease
#        eg. as area & no of bedroom goes up, price increases

In [4]:
# linear eq will be
#     price = m1 * area + m2 * bedrooms + m3 * age + b
#           -- price is dependent variable
#           -- area, bedrooms, age are features
#           -- m1, m2, m3 are coefficients 
#           -- b is intercept

In [5]:
#  topic to be covered are -  DATA HANDLING NA VALUES(DATA PREPROCESSING) 
#                          -  LR VIA MULTIPLE VARIABLES

In [28]:
import pandas as pd
import numpy as np
from sklearn import linear_model

In [43]:
df = pd.read_csv('D:\coding\Python\homeprice_Multi.csv')
df

area  bedrooms  age    price
0  2600       3.0    20  550000
1  3000       4.0    15  565000
2  3200       NaN    18  610000
3  3600       3.0    30  595000
4  4000       5.0     8  760000

In [44]:
# to fill missing value we will take median & use fillna()
import math
median_bedrooms = math.floor(df.bedrooms.median())
median_bedrooms

3

In [45]:
df.bedrooms = df.bedrooms.fillna(median_bedrooms)
df

area  bedrooms  age    price
0  2600       3.0    20  550000
1  3000       4.0    15  565000
2  3200       3.0    18  610000
3  3600       3.0    30  595000
4  4000       5.0     8  760000

In [46]:
reg = linear_model.LinearRegression()

In [49]:
reg = linear_model.LinearRegression()
reg.fit(df.drop('price',axis='columns'),df.price) 

# reg.fit(df[['area','bedrooms','age']],df.price)

LinearRegression()

In [50]:
reg.coef_

array([   137.25, -26025.  ,  -6825.  ])

In [51]:
reg.intercept_

383724.9999999998

In [52]:
#  price of home with 3000 sqr ft area, 3 bedrooms, 40 year old
reg.predict([[3000,3,40]])

C:\Users\MUSKAAN\Lib\site-packages\sklearn\base.py:420: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([444400.])

In [54]:
# m1 * area + m2 * bedrooms + m3 * year + intercept(b)

137.25 * 3000 + -26025. * 3 + -6825. * 40 + 383724.9999999998

444399.9999999998

In [57]:
#  price of home with 2500 sqr ft area, 4 bedrooms, 5 year old
reg.predict([[2500,4,5]])

C:\Users\MUSKAAN\Lib\site-packages\sklearn\base.py:420: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([588625.])

In [105]:
reg.predict([[1292,3,14]])

C:\Users\MUSKAAN\Lib\site-packages\sklearn\base.py:420: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([3688485.44395924])

In [100]:
reg.predict([[1132,3,8]])

C:\Users\MUSKAAN\Lib\site-packages\sklearn\base.py:420: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([3225181.22270742])

In [103]:
reg.predict([[1132,3,8]])

C:\Users\MUSKAAN\Lib\site-packages\sklearn\base.py:420: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([3225181.22270742])

In [58]:
# in this hiring data , as linear regression uses numbvers we will use word to number module

In [73]:
dff = pd.read_csv('D:\coding\Python\hiring.csv')
dff

experience  testscore  interviewscore  salary
0        NaN        8.0               9   50000
1        NaN        8.0               6   45000
2       five        6.0               7   60000
3        two       10.0              10   65000
4      seven        9.0               6   70000
5      three        7.0              10   62000
6        ten        NaN               7   72000
7     eleven        7.0               8   80000

In [77]:
median_testscore = dff.testscore.median() 
# figure out the missing value in (test score)


In [87]:
dff.testscore = dff.testscore.fillna(median_testscore)
dff

experience  testscore  interviewscore  salary
0        NaN        8.0               9   50000
1        NaN        8.0               6   45000
2       five        6.0               7   60000
3        two       10.0              10   65000
4      seven        9.0               6   70000
5      three        7.0              10   62000
6        ten        8.0               7   72000
7     eleven        7.0               8   80000

In [88]:
dff.experience = dff.experience.fillna('zero')
dff
# fill missing in (experience)

experience  testscore  interviewscore  salary
0       zero        8.0               9   50000
1       zero        8.0               6   45000
2       five        6.0               7   60000
3        two       10.0              10   65000
4      seven        9.0               6   70000
5      three        7.0              10   62000
6        ten        8.0               7   72000
7     eleven        7.0               8   80000

In [83]:
# here in experience col we need to fill values

from word2number import w2n

In [94]:
dff['experience'] = dff['experience'].astype(str).apply(w2n.word_to_num)

dff

experience  testscore  interviewscore  salary
0           0        8.0               9   50000
1           0        8.0               6   45000
2           5        6.0               7   60000
3           2       10.0              10   65000
4           7        9.0               6   70000
5           3        7.0              10   62000
6          10        8.0               7   72000
7          11        7.0               8   80000

In [96]:
reg = linear_model.LinearRegression()
reg.fit(dff[['experience','testscore','interviewscore']],dff.salary)

LinearRegression()

In [106]:
# predict for 2yr experience, 9 test score, 6 interview
reg.predict([[2,9,6]])

C:\Users\MUSKAAN\Lib\site-packages\sklearn\base.py:420: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([53205.96797671])